# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-23 08:11
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=100, unique=True, verbose_name='Наименование')),
                ('note_text', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('parallel_records', models.BooleanField(default=False)),
                ('start_work', models.TimeField(default=datetime.time(9, 0), verbose_name='Время начала работы установки')),
                ('end_work', models.TimeField(default=datetime.time(21, 0), verbose_name='Время окончания работы установки')),
                ('duration_of_record', models.DurationField(default=datetime.timedelta(1), verbose_name='Длительность записи')),
                ('unit_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_manager', to=settings.AUTH_USER_MODEL, verbose_name='Начальник установки')),
                ('unit_notice_users', models.ManyToManyField(blank=True, related_name='unit_notice', to=settings.AUTH_USER_MODEL, verbose_name='Уведомления')),
            ],
            options={
                'verbose_name': 'Установка',
                'verbose_name_plural': 'Установки',
                'ordering': ['unit_name'],
            },
        ),
        migrations.CreateModel(
            name='UnitSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_work', models.DateTimeField(verbose_name='Дата и время начала работы')),
                ('end_work', models.DateTimeField(verbose_name='Дата и время окончания работы')),
                ('test_object', models.CharField(max_length=20, verbose_name='Объект испытаний')),
                ('distance', models.IntegerField(choices=[(1, 'малое'), (2, 'среднее'), (3, 'большое')], default=2, null=True, verbose_name='Расстояние')),
                ('note_text', models.TextField(blank=True, help_text='Укажите режим и требуемые уровни', null=True, verbose_name='Примечания')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('edit_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменений')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_schedule', to=settings.AUTH_USER_MODEL)),
                ('tester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Испытатель')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='units.Unit', verbose_name='Установка')),
            ],
            options={
                'verbose_name': 'Запись на установку',
                'verbose_name_plural': 'Запись на установки',
                'ordering': ['-start_work'],
            },
        ),
        migrations.CreateModel(
            name='UnitUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tester', models.BooleanField(default=True, verbose_name='Испытатель')),
                ('boss', models.BooleanField(default=False, verbose_name='Руководитель НТГ')),
                ('superboss', models.BooleanField(default=False, verbose_name='Начальство')),
                ('notice_me', models.BooleanField(default=False, verbose_name='Получать уведомления')),
                ('note_text', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='units_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профайл',
                'verbose_name_plural': 'Профайлы',
                'ordering': ['user'],
            },
        ),
    ]
